package com.kbcoding.l39_nav_multiple_stacks.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006973)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF94F1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F24)
val md_theme_light_secondary = Color(0xFF006874)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF99F0FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F24)
val md_theme_light_tertiary = Color(0xFF48680E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC8F088)
val md_theme_light_onTertiaryContainer = Color(0xFF121F00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFD)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFAFDFD)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFF4FD8EA)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006973)
val md_theme_light_outlineVariant = Color(0xFFBFC8CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4FD8EA)
val md_theme_dark_onPrimary = Color(0xFF00363C)
val md_theme_dark_primaryContainer = Color(0xFF004F57)
val md_theme_dark_onPrimaryContainer = Color(0xFF94F1FF)
val md_theme_dark_secondary = Color(0xFF50D8EC)
val md_theme_dark_onSecondary = Color(0xFF00363D)
val md_theme_dark_secondaryContainer = Color(0xFF004F58)
val md_theme_dark_onSecondaryContainer = Color(0xFF99F0FF)
val md_theme_dark_tertiary = Color(0xFFADD36F)
val md_theme_dark_onTertiary = Color(0xFF223600)
val md_theme_dark_tertiaryContainer = Color(0xFF344E00)
val md_theme_dark_onTertiaryContainer = Color(0xFFC8F088)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E3)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFE1E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E3)
val md_theme_dark_inversePrimary = Color(0xFF006973)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4FD8EA)
val md_theme_dark_outlineVariant = Color(0xFF3F484A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF004A52)
val alternate = Color(0xFFE34AAE)
val light_alternate = Color(0xFFAE1782)
val light_onalternate = Color(0xFFFFFFFF)
val light_alternateContainer = Color(0xFFFFD8EA)
val light_onalternateContainer = Color(0xFF3C002A)
val dark_alternate = Color(0xFFFFAED9)
val dark_onalternate = Color(0xFF610046)
val dark_alternateContainer = Color(0xFF890065)
val dark_onalternateContainer = Color(0xFFFFD8EA)